### ISSUE TITLE
Trims Lost on X10 1.3.01 release

### ISSUE THREAD

**Issue by choochoo2** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#226]
When changing model memories, the trim settings are not retained when returning to the first model.

Also a suggestion;  When releasing a firmware version that was previously posted as a beta, please assign a new version number unless the release version is **IDENTICAL** to the beta.  In a situation like we have now with 1.3.01 beta and 1.3.01 release not being the same, the words "beta" and "release" effectively become part of the version number as they are needed to identify which version is being referenced.  That's what the version number should be for.

**Comment by MIKE-DAILEY** [comment]
Confirmed on 1.6.01 as well.

**Comment by Adelaxie** [comment]
trim setting？ trim setup？please  clarify which parameter or which page?thanks.

**Comment by choochoo2** [comment]
Lets say you fly airplane "A" and add 10 clicks of up-trim to obtain level flight and then change model memories to fly airplane "B", when you later return to airplane "A" the 10 clicks of trim you entered are gone and the trims are now back to neutral.  To fly airplane "A" again you must re-trim the plane.  You must re-trim each time you change aircraft.

**Comment by Woita2095** [comment]
I confirm the same behavior at described procedure.
The trims are cleared everytime the models are switched.
Please fix it ASAP, it is very severe bug. The radio is not possible to use for flying.

**Comment by Woita2095** [comment]
Confirmed the same behavior at the Horus X12s, FW 1.6.01L.

**Comment by Adelaxie** [comment]
Please help to confirm if its fixed on 
http://down.frsky-rc.com:8001/Adlea/.x10Beta0115.rar
http://down.frsky-rc.com:8001/Adlea/.x12Beta0115.rar

**Comment by choochoo2** [comment]
The link above fails on download attempts.

OK, now it works.

**Comment by MIKE-DAILEY** [comment]
Adela,

I’m not able to download from your links, but apparently from the user post on Gethub the saving trim issue is fixed.

Any update on the THs and TH% counter and acquiring the vairo problem fix?

Mike

**Comment by choochoo2** [comment]
1.3.02 beta seems to be moving in the right direction:

- The trims are retained when changing models
- The problem with curves in expo/rates is corrected.
- The problem with timer TH% still exists (did not check THs)
- It still contains the older S6Rconfig file. It should get the newer, corrected, file posted recently on GitHub.

**Comment by BazG2** [comment]
ok, think trims are ok now, cheers

**Comment by choochoo2** [comment]
The problems with trims and curves were corrected in 1.3.02.  The problems with the timers were corrected in 1.3.03 Beta, which also contains the updated SXR config so all four problems bulleted above are now corrected in 1.3.03 Beta.

**Comment by MIKE-DAILEY** [comment]
Congratulations to the FrSky developers to getting the fixes.
